---
version: "3.5"
services:
  wetty:
    build: .
    image: butlerx/wetty
    container_name: wetty
    tty: true
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      SSHHOST: 'wetty-ssh'
      SSHPORT: 22
      NODE_ENV: 'development'
    command: yarn start --sshhost redbrick.dcu.ie

  web:
    image: nginx
    volumes:
      - ./bin/nginx.template:/etc/nginx/conf.d/wetty.template
    ports:
      - "80:80"
    environment:
      - NGINX_DOMAIN=wetty.com
      - NGINX_PORT=80
      - WETTY_HOST=wetty
      - WETTY_PORT=3000
    command: /bin/bash -c "envsubst '$${NGINX_DOMAIN},$${NGINX_PORT},$${WETTY_HOST},$${WETTY_PORT}' < /etc/nginx/conf.d/wetty.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  wetty-ssh:
    build:
      context: .
      dockerfile: Dockerfile-ssh
    container_name: 'wetty-ssh'

networks:
  default:
    name: wetty
